language: node_js
sudo: false
matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "io.js"
before_script:
  - mysql -e 'create database insidewarehouse_utest;'
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "cKg77E+JAwoKKWFkBQUFzz19J7dxFMqdzvyEwJYWvSVqFTcSO9+/65JGb0sZv70bZT8A+QaQX7Ijtxcsq4DyfdN452luwUN57DRB0svRp/hRTSBHCGW4zrNC1XcPIJd+jW9TgSm8SfP//m1GezkQ0pMI5URuBgUWf1gkkmCvIOQ="
    on:
      tags: true
      node_js: "0.10"
