language: node_js
sudo: false
before_install:
  npm i -g npm
matrix:
  include:
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "io.js"
before_script:
  - mysql -e 'create database insidewarehouse_integration_test;'
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "Gl1GeNpnbUChIaxGaJfzcCDBqsLcONxuOd0gq4O9VcM21zxdxdijMi9N5Hxztd6Bqx22er4AF6SrNydhVSiwtP2ocvcD+E6bI1DURwpj3wUI4y9IDAwW1uPQtcfmcs8fmvuduCMo8YPEP4v3m9er2ruyUK6tPztOq+S4WwgWULw="
    on:
      tags: true
      node_js: "4"
